### ISSUE TITLE
Problem Loading pSCNN model

### ISSUE THREAD

**Issue by Ricmelis80** [yuxuanliao/pSCNN#1]
Dear Dr. Liao,

By testing your scripts in Google Golab environment, I encountered a problem in particular in the 'pSCNN.py' script when loading the model: indeed seems that scripts and related function ' load_pSCNN' are unable to correctly find dir and *.h5 and *.pkl files.

For more clarity, I can share you privately ( by email) my Drive dir with files and related .ipynb scripts.   

Thanks in advance!

**Comment by yuxuanliao** [comment]
There may be a problem with the path where you load test_nmr.h5 and test_nmr.pkl. In pSCNN.py, I used an absolute path in my workspace. You should change it to the address where you save test_nmr.h5 and test_nmr.pkl, you can use either an absolute path or a relative path.

**Comment by Ricmelis80** [comment]
Of course, I use a different path i.e. the local repository associated with my colab.py file.  But the problem still persists

**Comment by yuxuanliao** [comment]
I tested the code for scripts and related function ' load_pSCNN', which has successfully loaded test_nmr.h5 and test_nmr.pkl, and performed the prediction. Testload_pSCNN.ipynb, related code and data have been uploaded to https://github.com/yuxuanliao/pSCNN/releases/tag/pSCNN. Please refer to this for details. In addition, since I do not use Google Golab environment, it is possible that there is a problem with your environment. Please refer to the description below to install the pSCNN environment.

Installation:
Python 3.8.13 and TensorFlow (version 2.5.0-GPU)

The main packages can be seen in [requirements.txt](https://github.com/yuxuanliao/pSCNN/blob/main/requirements/pip/requirements.txt)

Install Anaconda https://www.anaconda.com/

Install main packages in requirements.txt with following commands:

 conda create --name pSCNN python=3.8.13
 conda activate pSCNN
 python -m pip install -r requirements.txt
 pip install tqdm
